meta-amd: mctp: enable mctpi3c and mctppcie
add support to bring up the mctpi3c and mctppcie interfaces,  and
to configure local endpoint on each interface.

usage:
bmc:~# amd-mctp-config -h
Configure MCTP interfaces and discover MCTP end points.
Usage: /usr/sbin/amd-mctp-config [-c][-d][-h][-u]
Options:
-c Delete the MCTP configuration
-d Trigger the MCTP discovery process
-h Display this help message
-u Bring up the MCTP interfaces
bmc:~#

tested: verified on Congo and Morocco

Signed-off-by: Mahesh Kurapati <mahesh.kurapati@amd.com>
Change-Id: I23cbcb3550ed38a25b577b7f310690004f4550e9

diff --git a/meta-amd/meta-sp7/recipes-networking/mctp/mctp/amd-mctp-config b/meta-amd/meta-sp7/recipes-networking/mctp/mctp/amd-mctp-config
--- a/meta-amd/meta-sp7/recipes-networking/mctp/mctp/amd-mctp-config
+++ b/meta-amd/meta-sp7/recipes-networking/mctp/mctp/amd-mctp-config
@@ -4,18 +4,17 @@ help()
     # Display Help
     echo "Configure MCTP interfaces and discover MCTP end points."
     echo
-    echo "Usage: $0 [-d][-h][-u]"
+    echo "Usage: $0 [-c][-d][-h][-u]"
     echo "Options:"
+    echo "-c Delete the MCTP configuration"
     echo "-d Trigger the MCTP discovery process"
-    echo "-u Bring up the MCTP interfaces"
     echo "-h Display this help message"
+    echo "-u Bring up the MCTP interfaces"
     echo
 }
 
+MCTP_NETWORK_ID=1
 MCTP_LOCAL_ENDPOINT_ID=8
-
-#get the array of mctp i2c interfaces
-mapfile -t MCTP_I2C_INTF_LIST < <(ifconfig -a|cut -d' ' -f 1|grep mctpi2c)
 
 #get the root i2c bus number if the mctp i2c interfaces are behind a switch
 ROOT_I2C_NUM=
@@ -30,54 +29,66 @@ mctp_i2c_root_intf_get()
     done
 }
 
-mctp_i2c_local_endpoint_id_set()
+mctp_local_endpoint_id_set()
 {
-    MCTP_I2C_INTF=$1
-    ENDPOINT_ID=$2
+    local OP=$1
+    local MCTP_INTF=$2
+    local ENDPOINT_ID=$3
 
-    if ! mctp addr add "${ENDPOINT_ID}" dev "${MCTP_I2C_INTF}" 2>&1 |
+    if ! mctp addr "${OP}" "${ENDPOINT_ID}" dev "${MCTP_INTF}" 2>&1 |
             logger -t amd-mctp-config; then
         #log the error and continue configuring
         logger -t amd-mctp-config \
-            "mctp addr add ${ENDPOINT_ID} dev ${MCTP_I2C_INTF} failed."
+            "mctp addr ${OP} ${ENDPOINT_ID} dev ${MCTP_INTF} failed."
     fi
 }
 
-#Configure the MCTP i2c interfaces
-# - link up the mctpi2c* interfaces
-mctp_i2c_intf_config()
+mctp_intf_config()
 {
-    MCTP_NETWORK_ID=1
 
-    if [ "${#MCTP_I2C_INTF_LIST[@]}" -eq 0 ]; then
+    # Use mapfile to read the contents of /sys/class/net and filter interfaces using awk
+    # $0 - interface name
+    #  ~ - pattern matching operator in awk
+    # shellcheck disable=SC2012
+    mapfile -t MCTP_INTF_LIST < <(ls /sys/class/net | awk -v pattern="mctp$1" '$0 ~ pattern {print $0}')
+    local LINK_STATE="$2"
+
+    if [ "${#MCTP_INTF_LIST[@]}" -eq 0 ]; then
         logger -t amd-mctp-config \
-            "No MCTP I2C interfaces are configured on the system."
+            "No MCTP $1 interfaces are configured on the system."
         return
     fi
-    for MCTP_I2C_INTF in "${MCTP_I2C_INTF_LIST[@]}"
+
+    if [ "$1" == "i2c" ]; then
+	unset "MCTP_INTF_LIST[-1]"
+    fi
+
+    for MCTP_INTF in "${MCTP_INTF_LIST[@]}"
     do
-        #bring up the interface
-        if ! mctp link set "${MCTP_I2C_INTF}" up net "${MCTP_NETWORK_ID}" 2>&1 |
+        #set the interface state
+        if ! mctp link set "${MCTP_INTF}" "$LINK_STATE" net "${MCTP_NETWORK_ID}" 2>&1 |
                 logger -t amd-mctp-config; then
             #log the error and continue bring up the next interface
             logger -t amd-mctp-config \
-                "mctp link set ${MCTP_I2C_INTF} up net ${MCTP_NETWORK_ID} failed."
+                "mctp link set ${MCTP_INTF} ${LINK_STATE} net ${MCTP_NETWORK_ID} failed."
+        else
+            if [ "$LINK_STATE" == "up" ]; then
+                #add local endpoint to the interface
+                mctp_local_endpoint_id_set "add" "${MCTP_INTF}" "${MCTP_LOCAL_ENDPOINT_ID}"
+            else
+                #delete local endpoint to the interface
+                mctp_local_endpoint_id_set "del" "${MCTP_INTF}" "${MCTP_LOCAL_ENDPOINT_ID}"
+            fi
+            MCTP_LOCAL_ENDPOINT_ID=$((MCTP_LOCAL_ENDPOINT_ID + 1))
         fi
-
-        #add local endpoint to the interface
-        mctp_i2c_local_endpoint_id_set "${MCTP_I2C_INTF}" "${MCTP_LOCAL_ENDPOINT_ID}"
-        MCTP_LOCAL_ENDPOINT_ID=$((MCTP_LOCAL_ENDPOINT_ID +1))
     done
-
-    # add the following log informaiton to journalctl
-    # will be helpful for system debug
-    mctp link show 2>&1 | logger -t amd-mctp-config
 }
 
 mctp_i2c_discover()
 {
-
     #prepare list of mctp i2c interfaces
+    # shellcheck disable=SC2012
+    mapfile -t MCTP_I2C_INTF_LIST < <(ls /sys/class/net | awk -v pattern=mctpi2c '$0 ~ pattern {print $0}')
     if [ "${#MCTP_I2C_INTF_LIST[@]}" -eq 0 ]; then
         logger -t amd-mctp-config \
             "No MCTP I2C interfaces are configured on the system."
@@ -99,18 +110,19 @@ mctp_i2c_discover()
         # prepare a list of i2c devices that are seen on the bus and are not
         # associated with any driver and issue the endpoint assignment command
         # to them.
-        #I2C_BUS_NUM=$(echo "$MCTP_I2C_INTF"|sed 's/mctpi2c//g')
         I2C_BUS_NUM=${MCTP_I2C_INTF//mctpi2c/}
-        for (( I2C_ADDR=8; I2C_ADDR<77; I2C_ADDR++ ))
-        {
+        I2C_ADDRS=$(i2cdetect -y "${I2C_BUS_NUM}" | cut -d':' -f 2 |
+                    grep -v "    0"|tr -dc '[0-9][a-f] ')
+        for I2C_ADDR in $I2C_ADDRS
+        #for (( I2C_ADDR=8; I2C_ADDR<119; I2C_ADDR++ ))
+        do
             busctl call au.com.codeconstruct.MCTP1 \
                 /au/com/codeconstruct/mctp1/interfaces/"${MCTP_I2C_INTF}" \
-                au.com.codeconstruct.MCTP.BusOwner1 \
-                AssignEndpoint \
-                ay 1 0x"${I2C_ADDR}" 2>&1 |
+                au.com.codeconstruct.MCTP.BusOwner1 AssignEndpoint \
+		ay 1 0x"${I2C_ADDR}" 2>&1 |
                     logger -t amd-mctp-config
                 logger -t amd-mctp-config "for 0x${I2C_ADDR}"
-        }
+        done
         logger -t amd-mctp-config \
             "Discovering MCTP endpoints on the $MCTP_I2C_INTF... Done."
 
@@ -137,11 +149,16 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-# Only MCTP Over I2C is supported
-while getopts ":dhu" OPTION; do
+while getopts ":cdhu" OPTION; do
     case $OPTION in
+	c) #cleanup the mctp configuration
+            mctp_intf_config "pcie" "down"
+            mctp_intf_config "i3c" "down"
+            mctp_intf_config "i2c" "down"
+            ;;
+
         d) # trigger the discovery process
-            mctp_i2c_discover
+            mctp_i2c_discover "$MCTP_I2C_NETWORK_ID"
             ;;
 
         h) # display Help
@@ -149,7 +166,13 @@ while getopts ":dhu" OPTION; do
             exit 0;;
 
         u) # type of interface
-            mctp_i2c_intf_config
+            mctp_intf_config "pcie" "up"
+            mctp_intf_config "i3c" "up"
+            mctp_intf_config "i2c" "up"
+
+            # add the following log informaiton to journalctl
+            # will be helpful for system debug
+            mctp link show 2>&1 | logger -t amd-mctp-config
             ;;
 
         *) # display Help
